spring:
  application:
    name: SpringBootBasics


management:
  endpoints:
    web:
      exposure:
        include: health, metrics
  endpoint:
    health:
      show-details: always
    metrics:
      export:
        exposed:
          metrics: "*"

